import { useCallback } from 'react';

// Mock data with more questions and categories
const mockQuestions = [
  {
    id: 1,
    question_text: "What is 2 + 2?",
    options: ["3", "4", "5", "6"],
    correct_answer: "4",
    category: "math"
  },
  {
    id: 2,
    question_text: "What is the capital of France?",
    options: ["London", "Berlin", "Paris", "Madrid"],
    correct_answer: "Paris",
    category: "geography"
  },
  {
    id: 3,
    question_text: "What is the main idea of this passage?",
    options: [
      "The author's childhood",
      "The importance of education",
      "The history of literature",
      "The impact of technology"
    ],
    correct_answer: "The importance of education",
    category: "Reading"
  },
  {
    id: 4,
    question_text: "What is the atomic number of Hydrogen?",
    options: ["1", "2", "3", "4"],
    correct_answer: "1",
    category: "science"
  },
  {
    id: 5,
    question_text: "In the sentence 'waiting by the back door', which option best maintains the parallel structure of the passage?",
    options: [
      "NO CHANGE",
      "that waited by the",
      "were waiting by the",
      "which waited by the"
    ],
    correct_answer: "NO CHANGE",
    category: "english"
  },
  {
    id: 6,
    question_text: "In the phrase 'was sitting on the kitchen table', which option best maintains the parallel structure?",
    options: [
      "NO CHANGE",
      "sat",
      "which sat",
      "that was sitting"
    ],
    correct_answer: "sat",
    category: "english"
  },
  {
    id: 7,
    question_text: "Which of the following procedures, in addition to Studies 1, 2, and 3, would best test whether the amount of heat generated by SF is related to the mass of the SF?",
    options: [
      "Following the design of Study 1 but using concrete canisters containing 0.4 metric tons of SF",
      "Following the design of Study 1 but using stainless steel canisters containing 0.8 metric tons of SF",
      "Following the design of Study 2 but determining the thermal conductivities of twice as much of each rock type",
      "Following the design of Study 3 but determining the rock temperatures 0.5 km from the sites of SF burial"
    ],
    correct_answer: "Following the design of Study 1 but using stainless steel canisters containing 0.8 metric tons of SF",
    category: "science"
  },
  {
    id: 8,
    question_text: "Based on Figure 1, which rock type shows the highest thermal conductivity at 0°C?",
    options: [
      "Rock salt",
      "Granite",
      "Basalt",
      "Shale"
    ],
    correct_answer: "Rock salt",
    category: "science"
  },
  // Add more questions as needed
];

export const useDatabase = () => {
  const getQuestions = useCallback(async (category?: string) => {
    // Simulate network delay
    await new Promise(resolve => setTimeout(resolve, 500));
    
    if (category) {
      return mockQuestions.filter(q => q.category.toLowerCase() === category.toLowerCase());
    }
    return mockQuestions;
  }, []);

  return {
    getQuestions
  };
};